name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "release-please-config.json"
      - ".release-please-manifest.json"
      - "admin/i18n/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "release-please-config.json"
      - ".release-please-manifest.json"
      - "admin/i18n/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ioBroker/testing-action-check@070b1f092f89f19651a1d344fe9461cebb5811ce # v1
        with:
          node-version: "20.x"
          type-checking: true
          lint: true

  adapter-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: ioBroker/testing-action-adapter@6a0eacfceb10a95eec95578012eb3ebc213715c3 # v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ubuntu-latest
          build: true

