name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "release-please-config.json"
      - ".release-please-manifest.json"
      - "admin/i18n/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "release-please-config.json"
      - ".release-please-manifest.json"
      - "admin/i18n/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ioBroker/testing-action-check@v1
        with:
          node-version: "20.x"
          type-checking: true
          lint: true

  adapter-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: ${{ matrix.node-version }}
          os: ubuntu-latest
          build: true

  adapter-tests-windows:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: ioBroker/testing-action-adapter@v1
        with:
          node-version: 22.x
          os: windows-latest
          build: true
